name: Daily Selenium Automation Run

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'   # 9:00 AM IST

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Verify Chrome Installation
        run: google-chrome --version

      - name: Run Selenium Tests
        run: mvn clean test
        working-directory: AutomationProjects_Restassured
